name: Website Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # - name: Test
      #   run: npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy prod
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.IP_ADDR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
              ./build.sh